# Generated by Django 5.2 on 2025-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="qty",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
