# Generated by Django 5.2 on 2025-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0003_generatedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="base_model_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="style_selections",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
