# Generated by Django 5.2 on 2025-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0004_generationtask_base_model_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="aspect_ratios_selection",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="performance_selection",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="generationtask",
            name="save_extension",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
