# Generated by Django 5.2 on 2025-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0005_generationtask_aspect_ratios_selection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationtask",
            name="aspect_ratios_selection",
            field=models.CharField(blank=True, default="1152*896", max_length=20),
        ),
        migrations.AlterField(
            model_name="generationtask",
            name="performance_selection",
            field=models.CharField(blank=True, default="Speed", max_length=50),
        ),
        migrations.AlterField(
            model_name="generationtask",
            name="save_extension",
            field=models.CharField(blank=True, default="png", max_length=10),
        ),
    ]
