# Generated by Django 5.2 on 2025-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0006_alter_generationtask_aspect_ratios_selection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("emoji", models.CharField(default="💡", max_length=4)),
                ("prompt", models.TextField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
